sudo: required
services:
  - docker

before_install:
  - docker build -t kpizzle/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=TRUE kpizzle/react-test npm test -- --coverage

after_success:
  - docker build -t kpizzle/multi-client ./client
  - docker build -t kpizzle/multi-nginx ./nginx
  - docker build -t kpizzle/multi-server ./server
  - docker build -t kpizzle/multi-worker ./worker
  # login into docker via the CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push created images to docker hub
  - docker push kpizzle/multi-client
  - docker push kpizzle/multi-nginx
  - docker push kpizzle/multi-server
  - docker push kpizzle/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: eu-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-2-380402590287
    bucker_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
      secure: $AWS_SECRET_KEY