sudo: required
services:
  - docker

before_install:
  - docker build -t kpizzle/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=TRUE kpizzle/react-test npm test -- --coverage

after_success:
  - docker build -t kpizzle/multi-client ./client
  - docker build -t kpizzle/multi-nginx ./nginx
  - docker build -t kpizzle/multi-server ./server
  - docker build -t kpizzle/multi-worker ./worker
